### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by mathialakan** [ROCmSoftwarePlatform/rocSPARSE#199]
CMake Error at CMakeLists.txt:58 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.

CMake Error at CMakeLists.txt:66 (message):
  'hcc' or 'hipcc' compiler required to compile for ROCm platform.

**Comment by ntrost57** [comment]
If you are not using install script, you need to specify a HIP compiler to use cmake (e.g. CXX=hcc cmake ..). Please see README.md for details.

**Comment by mathialakan** [comment]
Yes, I assigned the hcc compiler as shown in README.md, I used the following command

CXX=/opt/rocm/bin/hcc cmake -DBUILD_CLIENTS_TESTS=OFF -DBUILD_SHARED_LIBS=ON -DBUILD_CLIENTS_SAMPLES=ON -DBUILD_CLIENTS_BENCHMARKS=OFF -DBUILD_VERBOSE=OFF

and I received the above error.

But, if I use the same command inside the build/release, I have different error as follows,

CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

CMake Error: The source directory "../rocSPARSE/build/release" does not appear to contain CMakeLists.txt.

**Comment by ntrost57** [comment]
You need to give cmake the relative path to CMakeLists.txt file. If you want to build from `rocSPARSE/build/release`, the relative path to CMakeLists.txt would be `../..`

**Comment by mathialakan** [comment]
Then I got the error as previous,
CMake Error at CMakeLists.txt:58 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.


CMake Error at CMakeLists.txt:66 (message):
  'hcc' or 'hipcc' compiler required to compile for ROCm platform.


-- Configuring incomplete, errors occurred!

**Comment by ntrost57** [comment]
Did you clear your build directory before running cmake command?

**Comment by mathialakan** [comment]
Yes, nothing inside. I freshly created the directories build/release.

**Comment by ntrost57** [comment]
Can you paste the cmake output when running it on a clear build directory? What OS and cmake version are you using?

**Comment by mathialakan** [comment]
I am using cmake/3.15.2, linux OS (on summit) - nothing build in the directory
