### ISSUE TITLE
Missing one line in the example C code of rocsparse

### ISSUE THREAD

**Issue by chenyiaero** [ROCmSoftwarePlatform/rocSPARSE#200]
This line is missing:

#include "hip/hip_runtime.h"

**Comment by ntrost57** [comment]
Why is this line missing, and in which files?

**Comment by chenyiaero** [comment]
When using g++ instead of hipcc to build the code, we have to put his line, just tried yesterday.

**Comment by ntrost57** [comment]
You are right, I have added `hip_runtime_api.h` header to the example. It should now compile using g++ compiler.
Thanks for the hint!
