### ISSUE TITLE
rocsparse_dbsrmv undefined on CentOS 7.7

### ISSUE THREAD

**Issue by chenyiaero** [ROCmSoftwarePlatform/rocSPARSE#201]
Howdy,

I am developing AcuSolve GPU on AMD cards and am converting my cuda code to rocm/hip code. However in the version of rocm I have installed for CentOS 7.7., the BSR format is not available. While it appears on the document page. It is not defined in the header. I am wondering if ROCM will be newer on CentOS 8 and the functions will be included. Thanks! 

Below is the version info:

HIP version: 3.3.20126-2dbba46b
HCC clang version 10.0.0 (/data/jenkins_workspace/centos_pipeline_job_3.3/rocm-rel-3.3/rocm-3.3-19-20200328/centos/external/hcc-tot/llvm-project/clang 1ce0fe5e88b2124494b9500817b4c2c66bdfa5aa) (based on HCC 3.1.20114-6776c83f-1ce0fe5e88b )

**Comment by ntrost57** [comment]
BSR format will be made available with ROCm soon. In any case, you can download rocSPARSE source and compile it yourself using `install.sh` script. Please check the user documentation for details.
