### ISSUE TITLE
transA for rocsparse_csrmm?

### ISSUE THREAD

**Issue by fdmalone** [ROCmSoftwarePlatform/rocSPARSE#206]
### What is the expected behavior
Currently the documentation (https://rocsparse.readthedocs.io/en/master/usermanual.html#rocsparse-csrmm)  has a note saying only transA = rocsparse_operation_none is supported. Are there plans to update this for transpose and conjugate transpose?

### What actually happens
NA

### How to reproduce
NA

### Environment
NA

| Software | version |
rocm-3.5.0

**Comment by doctorcolinsmith** [comment]
Full support for all the operation options is currently being assessed for a future release.  We will update release notes as support is implemented.

**Comment by doctorcolinsmith** [comment]
This is now implemented.  You should be able to use it now from the develop branch, and it will be available in an upcoming release.
