### ISSUE TITLE
 [Build Error] [CMake] Cannot find hip

### ISSUE THREAD

**Issue by acxz** [ROCmSoftwarePlatform/rocSPARSE#207]
### What is the expected behavior
-  Including rocsparse in a cmake project like find_package(rocsparse) should be successful.

### What actually happens
-  When using find_package(rocsparse), it fails since it cannot find hip, even though hip is installed.

```
CMake Error at /usr/share/cmake-3.18/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "Findhip.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "hip", but
  CMake did not find one.

  Could not find a package configuration file provided by "hip" with any of
  the following names:

    hipConfig.cmake
    hip-config.cmake

  Add the installation prefix of "hip" to CMAKE_PREFIX_PATH or set "hip_DIR"
  to a directory containing one of the above files.  If "hip" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /opt/rocm/rocsparse/lib/cmake/rocsparse/rocsparse-config.cmake:89 (find_dependency)
  cmake/public/LoadHIP.cmake:131 (find_package)
  cmake/public/LoadHIP.cmake:169 (find_package_and_print_version)
  cmake/Dependencies.cmake:995 (include)
  CMakeLists.txt:411 (include)
```

FindHIP.cmake is installed on the system but Findhip.cmake is not.

### How to reproduce
-  Call `find_package(rocsparse)` in a cmake project.

### Environment
| Hardware | description |
|-----|-----|
| GPU | device string |
| CPU | device string |

| Software | version |
|-----|-----|
| ROCK | v3.5.1 |
| ROCR | v3.5.0 |
| HCC | N/A |
| Library | v3.5.0 |

Downstream issue: https://github.com/pytorch/pytorch/issues/41886

**Comment by acxz** [comment]
Closing this issue since this does not directly pertain to this repo but rather the lack of functionality in `FindHIP.cmake` in the HIP package.

**Comment by ntrost57** [comment]
Closing this issue since this does not directly pertain to rocsparse but rather the lack of functionality in FindHIP.cmake in the HIP package.

**Comment by acxz** [comment]
Linking upstream issue for tracedown: https://github.com/ROCm-Developer-Tools/HIP/issues/527
