### ISSUE TITLE
rocsparse fails to build in Manjaro with default setup

### ISSUE THREAD

**Issue by BishopWolf** [ROCmSoftwarePlatform/rocSPARSE#211]
### What is the expected behavior
- rocsparse builds using default `pamac install rocm-libs`

### What actually happens
- 
```
[ 68%] Building CXX object library/CMakeFiles/rocsparse.dir/src/conversion/rocsparse_nnz_compress.cpp.o
fatal error: error in backend: Cannot select: 0x55d580125888: i64 = FrameIndex<0>
In function: _Z41csrgemm_fill_block_per_row_device_pointerI21rocsparse_complex_numIdELj128ELj16ELj256ELj137EEviPKiS3_PKT_S3_S3_S6_S3_S3_S6_S6_S3_S3_S6_S3_PiPS4_21rocsparse_index_base_S9_S9_S9_bb
clang-11: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 11.0.0 (https://aur.archlinux.org/llvm-amdgpu.git 38fffda570a017745da11c40ed8991c3c70a3281)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
```

### How to reproduce
- `pamac install rocm-libs`

### Environment
| Hardware | description |
|-----|-----|
| GPU | Radeon 570X | 
| CPU | Ryzen 2700X | 
|-----|-----|
| Description | Manjaro Linux |
| Release | 20.1 |
| Codename |  Mikah |
 
|-----|-----|
| ROCK | v0.0 |
| ROCR | v0.0 |
| HCC | v0.0 |
| Library | v0.0 |

**Comment by ntrost57** [comment]
Hi BishopWolf, Arch Linux and it's derivatives are currently not supported by the ROCm stack. A list of supported operating systems can be found here.
