### ISSUE TITLE
2 failed tests from GoogleTestVerification.UninstantiatedParameterizedTestSuite<csrilusv>

### ISSUE THREAD

**Issue by littlewu2508** [ROCmSoftwarePlatform/rocSPARSE#227]
### What is the expected behavior
- rocsparse-test pass all the tests

### What actually happens
- 2 failed tests from GoogleTestVerification.UninstantiatedParameterizedTestSuite<csrilusv>, detailed info:
```
[----------] 2 tests from GoogleTestVerification
[ RUN      ] GoogleTestVerification.UninstantiatedParameterizedTestSuite<csricsv>
/tmp/portage/sci-libs/rocSPARSE-4.3.0/work/rocSPARSE-rocm-4.3.0/clients/tests/test_csricsv.cpp:89: Failure
Parameterized test suite csricsv is defined via TEST_P, but never instantiated. None of the test cases will run. Either no INSTANTIATE_TEST_SUITE_P is provided or the only ones provided expand to
 nothing.

Ideally, TEST_P definitions should only ever be included as part of binaries that intend to use them. (As opposed to, for example, being placed in a library that may be linked in to get other uti
lities.)

To suppress this error for this test suite, insert the following line (in a non-header) in the namespace it is defined in:

GTEST_ALLOW_UNINSTANTIATED_PARAMETERIZED_TEST(csricsv);
[  FAILED  ] GoogleTestVerification.UninstantiatedParameterizedTestSuite<csricsv> (0 ms)
[ RUN      ] GoogleTestVerification.UninstantiatedParameterizedTestSuite<csrilusv>
/tmp/portage/sci-libs/rocSPARSE-4.3.0/work/rocSPARSE-rocm-4.3.0/clients/tests/test_csrilusv.cpp:89: Failure
Parameterized test suite csrilusv is defined via TEST_P, but never instantiated. None of the test cases will run. Either no INSTANTIATE_TEST_SUITE_P is provided or the only ones provided expand t
o nothing.

Ideally, TEST_P definitions should only ever be included as part of binaries that intend to use them. (As opposed to, for example, being placed in a library that may be linked in to get other uti
lities.)

To suppress this error for this test suite, insert the following line (in a non-header) in the namespace it is defined in:

GTEST_ALLOW_UNINSTANTIATED_PARAMETERIZED_TEST(csrilusv);
[  FAILED  ] GoogleTestVerification.UninstantiatedParameterizedTestSuite<csrilusv> (0 ms)
```

### How to reproduce
- Compile rocSPARSE 4.3.0 with tests enabled, and run ./ rocsparse-test

### Environment
| Hardware | description |
|-----|-----|
| GPU | Vega 20 [Radeon VII] |
| CPU | AMD Ryzen 7 5800X |

| Software | version |
|-----|-----|
| Linux | 5.13.3 |
| ROCK | Upstream kernel |
| ROCR | v4.3.0 |
| HIPCC | v4.3.0 |
| Library | v4.3.0 |

**Comment by YvanMokwinski** [comment]
Hello,
What is the GoogleTest version you are using?

**Comment by littlewu2508** [comment]
> Hello,
> What is the GoogleTest version you are using?

Commit [aee0f9d9b5b87796ee8a0ab26b7587ec30e8858e](aee0f9d9b5b87796ee8a0ab26b7587ec30e8858e). It's after v1.10.0

**Comment by ntrost57** [comment]
I am not able to follow you. `test_csricsv.yaml` contains parameters for testing function `csricsv_file`, seems to be alright to me.
Could you give me step by step instructions on how to reproduce this issue within a gentoo docker container? gentoo/stage3 does not have rocm installed.

**Comment by littlewu2508** [comment]
> I am not able to follow you. `test_csricsv.yaml` contains parameters for testing function `csricsv_file`, seems to be alright to me. 
When I run tests the `csricsv_file` entry does not generate any actual test, and therefor test_csricsv.yaml does not contain actual tests which causes failure.Can you provide your test in your environment to see wthere there are csricsv tests executed or not?

> Could you give me step by step instructions on how to reproduce this issue within a gentoo docker container? gentoo/stage3 does not have rocm installed.

The gentoo/stage3 docker is too old. Please use the latest image:

https://ftp.lanet.kr/pub/gentoo//releases/amd64/autobuilds/20211101T001702Z/stage3-amd64-openrc-20211101T001702Z.tar.xz is the latest gentoo base image, but rocm is not installed by default. The detailed instructions are

```bash
# Prepare stage3 image
mkdir gentoo-stage3 && cd gentoo-stage3
wget https://ftp.lanet.kr/pub/gentoo//releases/amd64/autobuilds/20211101T001702Z/stage3-amd64-openrc-20211101T001702Z.tar.xz
tar -Jxf stage3-amd64-openrc-20211101T001702Z.tar.xz
for p in /proc /sys /dev /dev/pts /dev/shm;do mount -o bind $p .$p;done  # mount proc, sysfs, and tmpfs
cp /etc/resolv.conf etc/ # enable resolving after chroot

# Chroot, update repository and install deps
SHELL=bash chroot .
emere --sync # similar to apt update, update ebuild repository to latest
echo 'ACCEPT_KEYWORDS="~amd64"' | tee -a /etc/portage/make.conf # rocm-4.3 packages are currently marked as unstable, which is not available unless accepting ~amd64 keyword.
echo 'FEATURES="${FEATURES} -usersandbox -sandbox"' | tee -a /etc/portage/make.conf # there are some permission issue about /dev/kfd when testing in sandbox, so disable sandbox feature for convenience.
emerge --ask --onlydeps --verbose rocSPARSE # This should install all dependencies of rocSPARSE

# Compile rocSPARSE and test
echo 'AMDGPU_TARGETS="<foo>"' | tee -a /etc/portage/make.conf # set AMDGPU_TARGETS according to GPU. Replace <foo> with amdgpu targets such as gfx906:xnack- here. 
echo 'sci-libs/rocSPARSE test' | tee -a /etc/portage/package.use/00-rocSPARSE # enable test for rocSPARSE
ebuild /var/db/repos/gentoo/sci-libs/rocSPARSE/rocSPARSE-4.3.0-r1.ebuild compile # compile with test feature enabled
ebuild /var/db/repos/gentoo/sci-libs/rocSPARSE/rocSPARSE-4.3.0-r1.ebuild test # perform tests
```

**Comment by littlewu2508** [comment]
The root cause of this issue is that matrices are misplaced. csr files should be in ../matrices/ relative to rocsparse-test, but in gentoo those files are placed in ../../matrices/. It's quite hard to notice since gtest silently skip `*_file` tests in all test suites, leaving `csricsv_file` in an `UninstantiatedParameterizedTestSuite` status.

I created https://github.com/gentoo/gentoo/pull/22806 and gentoo will resolve it very soon. Currently I'm re-running tests with the correct matrices placing, and if there are any other failures I'll just open a new issue.

**Comment by ntrost57** [comment]
Thanks for reporting back. Please let me know if you observe any other testing failures on Gentoo.

**Comment by littlewu2508** [comment]
> 
> 
> Thanks for reporting back. Please let me know if you observe any other testing failures on Gentoo.

Currently rocSPARSE-4.3.0 tests passed on my machine (Radeon VII on Linux-5.13). In the future there will be more tests running by CI and users on different hardwares and driver versions.
