### ISSUE TITLE
csrmv behaves inconsistently with zero matrices if passing nullptr data

### ISSUE THREAD

**Issue by upsj** [ROCmSoftwarePlatform/rocSPARSE#234]
### What is the expected behavior
- hipsparseDcsrmv on an empty matrix (all zero row pointers) does not care about what is passed as column index and value array.

### What actually happens
- hipsparseDcsrmv computes the correct result (0) if we pass any non-null pointer, but leaves the output unmodified if we pass null pointers for column indices and values.

### How to reproduce
- Compile the following code and run it with either of the two hipsparseDcsrmv invocations. They should produce equivalent results, but one writes 0 to memory, the other one leaves the 0xCDCDCDCD values unchanged.

```cpp
#include <hipsparse.h>
#include <iomanip>
#include <iostream>

int main() {
  double *mem;
  int *zeros;
  double alpha{1.0};
  double beta{0.0};
  hipsparseHandle_t handle;
  hipMalloc(&mem, sizeof(double) * 3);
  hipMalloc(&zeros, sizeof(int) * 2);
  hipMemset(zeros, 0, sizeof(int) * 2);
  hipMemset(mem, 0xCD, sizeof(double) * 3);
  hipsparseCreate(&handle);
  hipsparseSetPointerMode(handle, HIPSPARSE_POINTER_MODE_HOST);
  hipsparseMatDescr_t descr;
  hipsparseCreateMatDescr(&descr);
#if 1
  hipsparseDcsrmv(handle, HIPSPARSE_OPERATION_NON_TRANSPOSE, 1, 1, 1, &alpha,
                  descr, nullptr, zeros, nullptr, mem, &beta, mem + 2);
#else
  hipsparseDcsrmv(handle, HIPSPARSE_OPERATION_NON_TRANSPOSE, 1, 1, 1, &alpha,
                  descr, (double *)1, zeros, (int *)1, mem, &beta, mem + 2);
#endif
  long result{};
  hipMemcpy(&result, mem + 2, sizeof(long), hipMemcpyDeviceToHost);
  std::cout << std::hex << result << std::endl;
  hipsparseDestroyMatDescr(descr);
  hipsparseDestroy(handle);
  hipFree(zeros);
  hipFree(mem);
}
```

### Environment
| Hardware | description |
|-----|-----|
| GPU | Radeon VII |
| CPU | AMD Ryzen Threadripper 1920X 12-Core Processor |

| Software | version |
|-----|-----|
| rocSPARSE | v1.20.2 |

**Comment by YvanMokwinski** [comment]
There is a problem here, the number of non-zeros you are specifying is 1 for a zero matrix.
So even with recent fixes regarding zero matrices in rocSPARSE, this code sample will continue to return an invalid status when passing null pointers because the number of non-zeros is wrong, indeed null pointers are not accepted if nnz > 0. Also hipsparseDcsrmv returns a status.

**Comment by YvanMokwinski** [comment]
Here is an updated version of your code sample, with few fixes (nnz=0 and transfer the result with int32 rather than int64)
No command line arguments will trigger the first call, any specified command line arguments will trigger the second call with fake non-null pointers.

Both runs will provide the same results.
./a.out
./a.out fake


```cpp
#include <hipsparse.h>
#include <iomanip>
#include <iostream>

int main(int argc, const char ** argv)
{
  int opt = 0;
  if (argc >= 2)
    {
      opt = 1;
    }

  double *mem;
  int *zeros;
  double alpha{1.0};
  double beta{0.0};
  hipsparseHandle_t handle;
  hipMalloc(&mem, sizeof(double) * 3);
  hipMalloc(&zeros, sizeof(int) * 2);
  hipMemset(zeros, 0, sizeof(int) * 2);
  hipMemset(mem, 0xCD, sizeof(double) * 3);
  hipsparseCreate(&handle);
  hipsparseSetPointerMode(handle, HIPSPARSE_POINTER_MODE_HOST);
  hipsparseMatDescr_t descr;
  hipsparseCreateMatDescr(&descr);

  hipsparseStatus_t status = HIPSPARSE_STATUS_SUCCESS;

  {
    if (opt == 0)
      {
        std::cout << "With null pointers" << std::endl;
        status = hipsparseDcsrmv(handle, HIPSPARSE_OPERATION_NON_TRANSPOSE, 1, 1, 0, &alpha,
                                 descr, nullptr, zeros, nullptr, mem, &beta, mem + 2);
      }
    else
      {
        std::cout << "With fake non-null pointers" << std::endl;
        status = hipsparseDcsrmv(handle, HIPSPARSE_OPERATION_NON_TRANSPOSE, 1, 1, 0, &alpha,
                                 descr, (double*)0x4, zeros, (int*)0x4, mem, &beta, mem + 2);
      }
    if (status != HIPSPARSE_STATUS_SUCCESS)
      {
        std::cerr << "invalid hipsparse status ( = " << status << " )" << std::endl;
        return status;
      }
  }

  int result{};
  hipMemcpy(&result, mem + 2, sizeof(int), hipMemcpyDeviceToHost);
  std::cout << std::hex << result << std::endl;

  hipsparseDestroyMatDescr(descr);
  hipsparseDestroy(handle);
  hipFree(zeros);
  hipFree(mem);

  return status;
}
```

**Comment by upsj** [comment]
Sorry for keeping this open so long, this was obviously not an issue from rocSPARSE's side.
