### ISSUE TITLE
Feature requests and useful instructions

### ISSUE THREAD

**Issue by klausbu** [ROCmSoftwarePlatform/rocSPARSE#275]
I adaped rocSparse (version rocSPARSE-rocm-5.4.1) to work with NAVI22 gfx1031 on RHEL 9.1 i.e. AlmaLinux 9.1.

I know, this architecture is not supported but implementing it as a target worked fine.

Feature requests probably relevant for other people as well:

1: Add AlmaLinux and Rocky_Linux to the install script. These are the most used RHEL bit-for-bit clones. I added "almalinux" and "AlmaLinux" and it worked fine.

2: Please mention the install script option -a gxf1031 (in my case) for compiling the source for a specific architecture to speed-up the process for such cases.

3: The tests ran for almost 3 hours, maybe you want to mention it next to the instructions so people know what to expect. A % of completion while the tests run would also be nice for people compiling the library from source.

Two out of the 283609 tests failed, maybe that's relevant for you:

[----------] Global test environment tear-down
[==========] 283609 tests from 331 test suites ran. (10227631 ms total)   
[  PASSED  ] 283607 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] nightly/csritilu0.precond/f64_c_505193_0b_4_rand, where GetParam() = { function: "csritilu0", index_type_I: "i32", index_type_J: "i32", compute_type: "f64_c", transA: "NT", transB: "NT", baseA: "0b", baseB: "0b", baseC: "0b", baseD: "0b", M: 505193, N: 505193, K: -1, nnz: -1, block_dim: 2, row_block_dimA: 2, col_block_dimA: 2, row_block_dimB: 2, col_block_dimB: 2, dim_x: 1, dim_y: 1, dim_z: 1, ll: -2, l: -1, u: 1, uu: 2, alpha: 1.0, alphai: 0.0, beta: 0.0, betai: 0.0, threshold: 1.0, percentage: 0.0, action: "num", part: "auto", matrix_type: "general", diag: "ND", uplo: "L", storage: "sorted", analysis_policy: "reuse", solve_policy: "auto", direction: "row", order: "col", format: "coo", itilu0_alg: "sync_split_fusion", sddmm_alg: "default", spmv_alg: "default", spsv_alg: "default", spsm_alg: "default", spmm_alg: "default", spgemm_alg: "default", sparse_to_dense_alg: "default", dense_to_sparse_alg: "default", gtsv_interleaved_alg: "default", gpsv_interleaved_alg: "default", matrix: "rand", matrix_init_kind: "default", file: "*", algo: 0, numeric_boost: 0, boost_tol: 0.0, boost_val: 1.0, boost_vali: 0.0, tolm: 1.0, name: "csritilu0", category: "nightly", hardware: "all", unit_check: 1, timing: 0, iters: 10, denseld: -1, batch_count: -1, batch_count_A: -1, batch_count_B: -1, batch_count_C: -1, batch_stride: -1 }

[  FAILED  ] nightly/csritilu0.precond/f64_c_505193_1b_4_rand, where GetParam() = { function: "csritilu0", index_type_I: "i32", index_type_J: "i32", compute_type: "f64_c", transA: "NT", transB: "NT", baseA: "1b", baseB: "0b", baseC: "0b", baseD: "0b", M: 505193, N: 505193, K: -1, nnz: -1, block_dim: 2, row_block_dimA: 2, col_block_dimA: 2, row_block_dimB: 2, col_block_dimB: 2, dim_x: 1, dim_y: 1, dim_z: 1, ll: -2, l: -1, u: 1, uu: 2, alpha: 1.0, alphai: 0.0, beta: 0.0, betai: 0.0, threshold: 1.0, percentage: 0.0, action: "num", part: "auto", matrix_type: "general", diag: "ND", uplo: "L", storage: "sorted", analysis_policy: "reuse", solve_policy: "auto", direction: "row", order: "col", format: "coo", itilu0_alg: "sync_split_fusion", sddmm_alg: "default", spmv_alg: "default", spsv_alg: "default", spsm_alg: "default", spmm_alg: "default", spgemm_alg: "default", sparse_to_dense_alg: "default", dense_to_sparse_alg: "default", gtsv_interleaved_alg: "default", gpsv_interleaved_alg: "default", matrix: "rand", matrix_init_kind: "default", file: "*", algo: 0, numeric_boost: 0, boost_tol: 0.0, boost_val: 1.0, boost_vali: 0.0, tolm: 1.0, name: "csritilu0", category: "nightly", hardware: "all", unit_check: 1, timing: 0, iters: 10, denseld: -1, batch_count: -1, batch_count_A: -1, batch_count_B: -1, batch_count_C: -1, batch_stride: -1 }

 2 FAILED TESTS

### Environment
| Hardware | description |
|-----|-----|
| GPU | gfx1031 |
| CPU | 5900HX |

| Software | version |
|-----|-----|
| ROCK | v rocm-5.4.1 |
| ROCR | v rocm-5.4.1 |
| HCC | v rocm-5.4.1 |
| Library | v rocSPARSE-rocm-5.4.1 |

**Comment by doctorcolinsmith** [comment]
@klausbu Thanks for submitting your feedback.

For (1), we do not officially support ROCm on Rocky or Alma linux at this time.  Though, it is good that you did not encounter any issues enabling it in your own build.  If you find problems on non-supported platforms, I encourage you to still file an issue on GitHub.

I will follow up internally about documentation improvements on items (2) and (3).
