### ISSUE TITLE
develop branch seems to have a different behavior for choosing general or adaptive csrmv

### ISSUE THREAD

**Issue by ex-rzr** [ROCmSoftwarePlatform/rocSPARSE#279]
### What is the expected behavior

I'm not sure. Advice required.

### What actually happens

1. I've noticed that traces/profiles contain different kernels when I use the release version of rocSPARSE (ROCm 5.4.2) and the current develop branch.
In my case (PETSc) `hipsparseSpMV` is used with CSR matrices without calling `hipsparseSpMV_preprocess` before.
rocm-5.4.2 launches `csrmvn_adaptive_kernel`, develop launches `csrmvn_general_kernel`.
  Does it mean that the old version preprocesses the matrix implicitly and the new version requires an explicit call `hipsparseSpMV_preprocess` (i.e. `rocsparse_spmv(..., rocsparse_spmv_stage_preprocess, ...)`)?

2. `rocsparse-bench -f csrmv` also changed its behavior, but it's strange that it is inconsistent when verification is used:
develop launches  `csrmvn_general_kernel`, with `--verify 1` it launches  `csrmvn_adaptive_kernel`.
rocm-5.4.2 uses `csrmvn_adaptive_kernel` for both cases.

### How to reproduce

```
./rocsparse-bench -f csrmv --precision s --bench-x --rocalution ${ROCSPARSE_BENCH_DATA_DIR}/*.csr --iters 10 --bench-n 1
```

```
rocsparse-bench -f csrmv --precision s --bench-x --rocalution ${ROCSPARSE_BENCH_DATA_DIR}/*.csr --iters 10 --bench-n 1 --verify 1
```

### Environment
| Software | version |
|-----|-----|
| Library | current develop [e77b2befaf17e8c8dd9b8b64d03237bebf46f9e8](https://github.com/ROCmSoftwarePlatform/rocSPARSE/commit/e77b2befaf17e8c8dd9b8b64d03237bebf46f9e8) and [rocm-5.4.2](https://github.com/ROCmSoftwarePlatform/rocSPARSE/releases/tag/rocm-5.4.2) |

**Comment by ntrost57** [comment]
I have found a bug in the benchmark tool. Thanks for reporting this @ex-rzr

**Comment by doctorcolinsmith** [comment]
The fix for this is in our develop branch and will appear in an upcoming release.
