### ISSUE TITLE
rocsparse_spsm compute stage synchronization

### ISSUE THREAD

**Issue by jakub-homola** [ROCmSoftwarePlatform/rocSPARSE#323]
### What is the expected behavior
compute stage of `rocsparse_spsm` executes asynchronously. The `rocsparse_spsm` call should take next to no time when stage = compute.

### What actually happens
the `rocsparse_spsm` function with stage = compute seems to wait for previous operations in the stream to finish, and therefore takes a long time

### How to reproduce
I was testing it on LUMI-G. Load modules with
```
module load LUMI/22.08 rocm/5.2.3
```
Compile the program [source.cpp.txt](https://github.com/ROCmSoftwarePlatform/rocSPARSE/files/11615431/source.cpp.txt) with
```
hipcc -g -O2 -fopenmp --offload-arch=gfx90a:sramecc+:xnack- source.cpp -o program.x -lrocsparse
```
(remove the .txt extension from the source file, github did not allow me to upload .cpp file...) and run with `./program.x`

It creates an upper-triangular matrix full of ones in CSR format, copies it to the device, creates the right-hand-side and solution matrices (single-column), performs the three spsm stages and deletes everything. There are timers for the spsm stages to see how long they take to submit and execute. I also added a dummy kernel launch before the calls to highlight that in the compute stage, there is a synchronization somewhere.

The output of the reproducer program was the following for my tests:
```
Allocate memory
Populate matrix in host memory
Copy matrix to device memory
Set vectors
Initialize sparse handle and descriptors
Buffersize
  Submitting long kernel
  Long kernel submitted
  Submitting the buffersize
  Buffersize submitted: 0.012159 ms
  Waiting for buffersize to finish
  Buffersize finished: 3417.359114 ms
Allocate buffer
Preprocess
  Submitting long kernel
  Long kernel submitted
  Submitting the preprocess
  Preprocess submitted: 3426.814079 ms
  Waiting for preprocess to finish
  Preprocess finished: 0.009060 ms
Compute
  Submitting long kernel
  Long kernel submitted
  Submitting the compute
  Compute submitted: 3432.324886 ms
  Waiting for compute to finish
  Compute finished: 390.285015 ms
Waiting for everything to finish
Everything finished: 0.000000 ms
Destroy sparse handle and descriptors
Free memory
Program finished
```

Notice the `Compute submitted: 3432.324886 ms` line, which states, that the compute stage took almost 3.5 seconds to submit - it was waiting for the previous kernel to finish.

### Environment

LUMI supercomputer, gpu node, SUSE Linux Enterprise Server 15 SP4, AMD EPYC 7A53 64-core, MI250X gfx90a:sramecc+:xnack-

rocm-5.2.3

Additionally, I would like to ask, does the preprocessing stage of spsm and spsv really have to be synchronous? The function itself (not including the synchronization) does not take much time per my measurements, so it is not a huge deal, but it would be nice if it was asynchronous too.

Thanks,

Jakub

**Comment by ntrost57** [comment]
Has been fixed in develop and will appear in a future rocm release.
