### ISSUE TITLE
rocsparse_spmm dense matrices have to have same order

### ISSUE THREAD

**Issue by jakub-homola** [ROCmSoftwarePlatform/rocSPARSE#333]
I was having trouble using the `rocsparse_spmm` function, the solve stage (only the solve stage) kept returning an error `rocsparse_status_invalid_value`. After a while of searching, I found [this if](https://github.com/ROCmSoftwarePlatform/rocSPARSE/blob/28426e6205f3aee97b3cb90329611aaf541dc811/library/src/level3/rocsparse_csrmm.cpp#L672) in the source code, only allowing dense matrices `B` and `C` with the same storage order (row major or column major). Okay, this might make sense, since it's another case to implement (although cuSPARSE has no problem with that). But I could not find any info about this restriction [in the documentation](https://rocsparse.readthedocs.io/en/rocm-5.5.1/usermanual.html#rocsparse-spmm).

Please add a note about this to the docs (and please take a look at other functions if the same problem isn't there too).

---

Also, as a sidenote, please improve the error reporting (across all ROCm libraries). As far as I remember, CUDA libraries print an actually helpful error message before returning the status/error code.

**Comment by jsandham** [comment]
@jakub-homola Thanks for bringing this to our attention.I am currently investigating allowing different `rocsparse_order` for both `B` and `C` matrices. Ill report back once I have a working PR.

I agree on your side note about improving the error reporting. Ill bring this up at our next group meeting.

**Comment by jsandham** [comment]
@jakub-homola I have merged the fix (https://github.com/ROCmSoftwarePlatform/rocSPARSE/commit/b13e637195f65d8e02ac554f0ee532d2aea11829) that allows using mixed `rocsparse_order` for the dense 'B' and 'C' matrices in SpMM to the develop branch. We are targeting this for rocm-6.0 release. I can also report that we are currently working on improving the logging also targetted for the rocm-6.0 release.

**Comment by jakub-homola** [comment]
Awesome, thanks :)
