### ISSUE TITLE
Enable gfx1010 by default in rocSPARSE builds

### ISSUE THREAD

**Issue by ulyssesrr** [ROCmSoftwarePlatform/rocSPARSE#348]
https://github.com/ROCmSoftwarePlatform/rocSPARSE/blob/a1c59eaacdc8c4e31923321bfa3242fb265f6949/CMakeLists.txt#L155

https://github.com/ROCmSoftwarePlatform/rocSPARSE/blob/a1c59eaacdc8c4e31923321bfa3242fb265f6949/CMakeLists.txt#L160

### What is the expected behavior
I am aware that gfx1010 is not officially supported, yet I believe that some of the architectures quoted above(ie: gfx803) are not supported either, additionally gfx1010 is enabled by default on rocBLAS. I'm building rocSPARSE for gfx1010 successfully on both [Arch Linux](https://aur.archlinux.org/packages/rocsparse-gfx1010) and [Ubuntu](https://github.com/ulyssesrr/docker-rocm-gfx803/blob/main/rocm-xtra-builder-rocsparse/Dockerfile), it works, so ideally gfx1010 could be added to the default targets in the same unsupported way. This would hopefully cascade to downstream distros and lower ROCm friction.

### What actually happens
gfx1010 is not built by default :slightly_frowning_face:

### How to reproduce
Standard build.

### Environment
| Hardware | description |
|-----|-----|
| GPU | AMD Radeon RX 5700 XT |

| Software | version |
|-----|-----|
| ROCM | v5.6.0 |

**Comment by jsandham** [comment]
@ulyssesrr Thanks for the suggestion. Let me talk to the team and I will get back to on whether we can add this additional target.

**Comment by serhii-nakon** [comment]
@doctorcolinsmith @jsandham Hello, I have a question. What exactly not fully supported for now? 
I found this thread https://www.reddit.com/r/ROCm/comments/1bd8vde/comment/kvux38v/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button that looks like should works in 6.1 release. Does it correct?

**Comment by cgmb** [comment]
If rocSPARSE is built for gfx1010, it will work on gfx1010. The ROCm binary packages are not built for gfx1010, but you can build rocSPARSE from source or install a third-party package that is built for your architecture (such as the librocsparse0 package on Ubuntu 23.10 or Debian Trixie).

The thread you linked is just saying that rocBLAS now works with Tensile lazy loading and separate architectures on gfx1010 if rocBLAS has been built for gfx1010.

**Comment by cgmb** [comment]
Although, I suppose it's relevant to note that rocBLAS has historically been built for gfx1010 in AMD official releases. The gfx1010 target was enabled in the same commit that enabled gfx1030. The rocSOLVER library matched rocBLAS soon after, but to my knowledge, no other libraries have been built for gfx1010 in AMD's binary packages.

**Comment by serhii-nakon** [comment]
@cgmb Hello, I mean enable gfx1010 by default to allow use prebuilt rocm and pytorch without recompiling things that should works out of box usually. I mean that for example Nvidia allow to use older cards why AMD does not (even in case when it technically possible, even with status unofficially supported)? 

I would like to get working Pytorch/Tensorflow out of box for gfx1010 without recompiling (Recompiling usually require 26-30Gb of RAM and spend few hours just to get pytorch working)

*Out of box I mean Docker rocm/pytorch or tensorflow

**Comment by doctorcolinsmith** [comment]
@serhii-nakon To confirm, gfx1010 is not officially supported in the shipped ROCm packages.  It will likely be removed from rocBLAS and rocSOLVER in an upcoming release.

**Comment by serhii-nakon** [comment]
@doctorcolinsmith But why? It even more worst than before...

I mean that currently I can rebuild only some parts of rocm but you will remove it fully... Can you explain why gfx1010 can not be provided at the same way as gfx1030?

**Comment by serhii-nakon** [comment]
@doctorcolinsmith I already has answer for those questions https://github.com/ROCm/ROCm/issues/1735#issuecomment-2032752765
