### ISSUE TITLE
rocsparse_dense2csr creates CSC matrix

### ISSUE THREAD

**Issue by luspi** [ROCmSoftwarePlatform/rocSPARSE#358]
### What is the expected behavior
Converting a dense matrix to CSR format using `rocsparse_dense2csr()` should result in a matrix encoded in CSR format.

### What actually happens
The resulting matrix is encoded in CSC format.

### How to reproduce
Convert a dense matrix to CSR format using rocsparse and look at result. I attached a test code that shows this behavior. It returns the following output:

```
Matrix:
  1  2  3  4  5
  6  7  8  9 10
 11 12 13 14 15
 16 17 18 19 20
 21 22 23 24 25

row_ptr = 0, 5, 10, 15, 20, 25
col_ind = 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 
val = 1 6 11 16 21 2 7 12 17 22 3 8 13 18 23 4 9 14 19 24 5 10 15 20 25
```

### Environment
| Hardware | description |
|-----|-----|
| GPU | MI100 |
| CPU | AMD 7763 |

| Software | version |
|-----|-----|
| ROCM | v5.7.0 |

### Attachments

[csrcsc.zip](https://github.com/ROCmSoftwarePlatform/rocSPARSE/files/13288970/csrcsc.zip)

**Comment by YvanMokwinski** [comment]
Our mistake is the documentation. The dense matrix must be stored with a column-oriented layout. We do not cover the row-oriented one, and it is impossible to specify it with the current API. We will fix the documentation.

**Comment by luspi** [comment]
Ah, thanks! I did notice that rocsparse_dense2csc can be used in this case instead. It might be nice to have this as a parameter that switches between the two versions in the backend accordingly.

**Comment by YvanMokwinski** [comment]
I hear you, but this would require a change of API since the row-oriented or the column-oriented storage of the dense matrix cannot be specified with the current one. To be consistent, we would also have to provide this flexibility to other operations like csrmm, for instance. 
We are consistent with rocBLAS, which requires dense matrices with a column-oriented layout. Most likely, we will keep this that way.

**Comment by luspi** [comment]
That makes a lot of sense.

I got stuck there for a bit when converting the dense matrix returned by `rocsparse_ccsritilu0_compute()` to csr format. It appears that that routine returns a dense matrix with a row-oriented layout.

**Comment by YvanMokwinski** [comment]
Sorry, which dense matrix rocsparse_csritilu0_compute is returning? I am not sure I understand.

**Comment by luspi** [comment]
Oh, I meant the `ilu0` parameter containing the incomplete factorization after a call to that function.

**Comment by YvanMokwinski** [comment]
This is not a dense matrix; this is the array of values of the incomplete factorization attached to the specified sparsity pattern.

**Comment by luspi** [comment]
Oh, it will have the same sparsity pattern as the input matrix? That would be pretty great actually.

**Comment by YvanMokwinski** [comment]
No worries
