### ISSUE TITLE
rocsparse_spsm doesn't return the correct result with transb = rocsparse_operation_transpose 

### ISSUE THREAD

**Issue by amontoison** [ROCmSoftwarePlatform/rocSPARSE#365]
### What is the expected behavior
- `rocsparse_spsm` should return the correct result of `op(A) * x = transpose(B)`.

### What actually happens
- A wrong solution is returned.

### How to reproduce
- Solve any triangular system with multiple right-hand sides with `transb = rocsparse_operation_transpose`.
- We also have a reproducer in the Julia interface [AMDGPU.jl](https://github.com/JuliaGPU/AMDGPU.jl/pull/567).

### Environment
- HIP Runtime v5.6.31062
- rocBLAS v3.0.0
- rocSOLVER v3.22.0
- rocALUTION  (the version with rocm-5.6.1)
- rocSPARSE (the version with rocm-5.6.1)
- rocRAND v2.10.5
- rocFFT v1.0.21
-  MIOpen v2.20.0
- HIPDevice(name="AMD Radeon RX 6700 XT", id=1, gcn_arch=gfx1030)

**Comment by YvanMokwinski** [comment]
Thank you for your feedback.
Let's have a look at that.

**Comment by YvanMokwinski** [comment]
I just ran a tiny example aside from our unit tests. I would suggest you give me more details, such as the parameters passed to SpSM. Please provide data to reproduce what you are observing.

**Comment by amontoison** [comment]
For the tests, we have this Julia code:
```julia
for SparseMatrixType in (ROCSparseMatrixCSR, ROCSparseMatrixCSC, ROCSparseMatrixCOO)
  @testset "$SparseMatrixType -- sm! algo=$algo" for algo in (rocSPARSE.rocsparse_spsm_alg_default,)
        @testset "sm! $T" for T in [Float32, Float64, ComplexF32, ComplexF64]
            @testset "transa = $transa" for (transa, opa) in [('N', identity), ('T', transpose), ('C', adjoint)]
                @testset "transb = $transb" for (transb, opb) in [('N', identity), ('T', transpose)]
                    @testset "uplo = $uplo" for uplo in ('L', 'U')
                        @testset "diag = $diag" for diag in ('U', 'N')
                            A = rand(T, 10, 10)
                            A = uplo == 'L' ? tril(A) : triu(A)
                            A = diag == 'U' ? A - Diagonal(A) + I : A
                            A = sparse(A)
                            dA = SparseMatrixType(A)
                            B = transb == 'N' ? rand(T, 10, 2) : rand(T, 2, 10)
                            C = rand(T, 10, 2)
                            dB = ROCArray(B)
                            dC = ROCArray(C)
                            alpha = rand(T)
                            rocSPARSE.sm!(transa, transb, uplo, diag, alpha, dA, dB, dC, 'O', algo)
                            @test opa(A) \ (alpha * opb(B)) ≈ collect(dC)
                        end
                    end
                end
            end
        end
    end
end
```
and all combinations with `transb = 'T'` are failing.

**Comment by YvanMokwinski** [comment]
Can you give me data I can work with?

**update**

I am able to reproduce the problem, a problem which is not reported in our tests... I'll need to figure out this.
We will correct the situation, thank you for reporting.

**Comment by amontoison** [comment]
A little bit off-topic, for `spsv` we can't use a different descriptor for the sparse matrix if we want to reuse the `buffer` and the `analysis` for solving new triangular systems with the same structure.
We don't have this issue with `spsm`.
As a workaround, we update the descriptor with the routines `rocsparse_coo_set_pointers` or `rocsparse_csr_set_pointers`.

cc @michel2323

**Comment by YvanMokwinski** [comment]
I am actually surprised you don't have this issue with SpSM; I'll look at it.
This is an API issue; thus, internal data structures produced during the analysis are attached to the matrix descriptor. We want to address this important design flaw, which exists for several reasons, by having an explicit routine descriptor (rocsparse_spsv_descr) to hold these data structures instead. 
Consider your matrix descriptor as an SpSV descriptor as you currently do until a new API emerges.

**Comment by YvanMokwinski** [comment]
Note: you don't have to 'reuse' the buffer; nothing is stored there.

**Comment by amontoison** [comment]
So it's mean we can use a null pointer for the step `rocSPARSE.rocsparse_spsv_stage_compute` or `rocsparse_spsm_stage_compute`?
We keep the `buffer_size` and the `buffer` in a structure to solve different triangular systems in our Julia code [here](https://github.com/JuliaSmoothOptimizers/KrylovPreconditioners.jl/blob/main/ext/AMDGPU/operators.jl#L98-L166).

**Comment by YvanMokwinski** [comment]
I meant you don't need to freeze a buffer for the exclusive usage of spsv/spsm, you can perfectly reuse this buffer for something else or deallocating and reallocating when needed. 
Another thing we tend to consider is having two separate buffer sizes, one for the analysis and one for the computation. A big buffer required from the analysis but not used in the compute phase is a waste of resources.

**Comment by YvanMokwinski** [comment]
This is fixed.

Known bug test introduced here:
https://github.com/ROCm/rocSPARSE/commit/06e9fcba8c6e016847c8e87ac812d1fc6f8dce67

SpSM refactoring:
https://github.com/ROCm/rocSPARSE/commit/bb22be0101d8d41e4a719c0f39eec8d5ca6d5455

Thank you.
