### ISSUE TITLE
[issue or Feature Request] extract the strictly lower part, diagonal, invert the diagonal, add-subtract matrices, deal with fill-inn?

### ISSUE THREAD

**Issue by klausbu** [ROCmSoftwarePlatform/rocSPARSE#366]
**Does rocsparse support the following operations**: I can't find them, I hope I have been looking in the wrong spot but ChatGPT  couldn't find these operations either.

Given a sparse, SPD matrix A stored on the GPU in CSR format using rocThrust vectors, there will be no host-device transfers, the application runs on the GPU once the initial data has been transferred to the GPU. This is part of the development of an AINV preconditioner.

**1: compute the matrix K1 = I-L*D⁻1** where I is the identity matrix, L the stricktly lower part of A, and D⁻1 the invers diagonal of A

**2: compute the matrix K2 = I-D⁻1*L^T** where I is the identity matrix, L^T the transpose of the stricktly lower part of A, and D⁻1 the invers diagonal of A

**3: compute the matrix P = K1*K2** >> use rocsparse_dcsrmm(); this is possible how about 1: and 2: **extract the strictly lower part, diagonal, invert the extracted diagonal, add-and-subtract matrices, deal with fill-inn (support thresholds)?**  

I am using ROCm 5.7.1 on (RHEL) Almalinux 9.3 and I tested rocALUTION for the application which uses all these operations but due to its host-device approach it's not suitable for the application which is about on-device computation over thousands of timesteps.

**Comment by ntrost57** [comment]
We will look into adding subroutines to extract (strictly) lower and upper triangular matrices in one of our future releases.
It is however not clear to me, why rocalution does not work for you. You can exclusively work on the device when using rocalution. Data does not necessarily need to be copied e.g. from host.

**Comment by ppanchad-amd** [comment]
@klausbu Can you please test rocALUTION with ROCm 6.1.2 to see if your issue is resolved? Thanks

**Comment by ppanchad-amd** [comment]
@klausbu Closing ticket due to lack of response.  Please re-open ticket if you still need assistance after testing with the latest ROCm 6.2. Thanks!

**Comment by ntrost57** [comment]
Closing this issue as extracing triangular matrices is not supported by rocsparse.
