### ISSUE TITLE
Feature request: Separate workspace buffers to persistent and temporary

### ISSUE THREAD

**Issue by jakub-homola** [ROCmSoftwarePlatform/rocSPARSE#369]
As I can see in the implementation of e.g. the `rocsparse_Xcsrsm_buffer_size` function (e.g. [here](https://github.com/ROCm/rocSPARSE/blob/456a62eff6149fbcad5d0b2d169192c85cc778c2/library/src/level3/rocsparse_csrsm_buffer_size.cpp#L33), there are two kinds of memory needed in a buffer.

One part of the buffer memory is to store some helper data about the CSR matrix itself, e.g. the transposed matrix. This memory is initialized once in the analysis stage, and then just read in the solve stage. It is __persistent__ between multiple calls to the solve stage.

The other part of the buffer memory is used in the solve stage only. As I can see in the function I linked, you might need additional memory of the size of the RHS matrix (for a possible transposed copy of B). This memory is only used in the solve stage as a __temporary__ buffer, and the data it contains is not needed before or after the solve stage, the memory can be reused for other things (e.g. a solve with a different matrix).

(am I right, does it work this way?)

My request is to split these two kinds of workspace buffers to two, so that I don't have to keep allocated the whole buffer with the huge RHS for multiple CSR matrices at the same time.

In my use case, I have a set of ~100 of CSR matrices with their RHSs (~20000 size of matrix, ~4000 righ-hand-sides per matrix). csrsm buffer_size reports that it requires ~600 MB of memory, which totals ~60 GB for all matrices (just barely enough to fit on a MI250X GCD, not counting the original matrix data). I sequentially loop through all these matrices and perform the analysis phase. Then, I loop throuh them again and perform the solve phase. This solve loop is again in a loop, so each matrix is used multiple times for solve (so separating the analysis and solve makes sense, I don't want to re-analyze the matrix before each solve, even though it is quite fast now). As you can see, the workspace buffers for the RHSs do not all need to be allocated at the same time, I could just allocate the largest one and use it for all solves.

(my actual use case is slightly different, but this demonstrates the main point I am trying to make)

I understand this is a very specific use case and large matrices, and it would add another boilerplate code to using rocsparse, but I think that separating the workspace buffers (in all functions, not just csrsm) might have other uses than mine.

---

Edit:

So after reading through the source code of rocsparse more carefully, my memory problem can be solved by just using a transposed RHS matrix B.

Although it is an implementation detail, I think these things (like "the function will need a large workspace buffer if `transB==none`" or "this function is faster if `transA==trans`") should be mentioned in the documentation - after all, this is HPC, we care about performance and memory; and don't want to test all possible variants of calling the function to find the fastest.

Anyway, this moves my feature request to a very low priority for me. So feel free to close this issue after you read it :)

(and sorry for using this issue as a rubber ducky)

**Comment by ntrost57** [comment]
Thanks for your input. We will look into it and update the user manual accordingly.

**Comment by ppanchad-amd** [comment]
@ntrost57 Is the user manual updated? If not, I can create an internal ticket to fix the user manual. Thanks!

**Comment by jsandham** [comment]
@ppanchad-amd Please create internal ticket.
