### ISSUE TITLE
Question about reporting performance of AMD MI250 Accelerator

### ISSUE THREAD

**Issue by pmpakos** [ROCmSoftwarePlatform/rocSPARSE#398]
Hello
I do not have any issue with rocSPARSE, but I do not know where else to ask...

When writing a simple program and running it on an AMD MI250 GPU, it runs on 1 out of 2 GCDs of the MI250.
In rocm-smi I can see two "separate" GPUs existing, and only one of them is occupied during running the benchmark.

Should I rewrite my program to run on the two GCDs, when running a performance benchmark for this GPU, or leave it as it is, underutilizing the available hardware?

What is the direction that you (the developers of rocSPARSE) follow, when reporting performance of rocSPARSE?

Thank you.

**Comment by ntrost57** [comment]
Typically, we benchmark using a single GCD. But you could also use 2 GCDs if you prefer.
